# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/HDMI.xdc

# Block Designs: bd/ZYNQ_CORE/ZYNQ_CORE.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE || ORIG_REF_NAME==ZYNQ_CORE} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_processing_system7_0_0/ZYNQ_CORE_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_CORE_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_vdma_0_1/ZYNQ_CORE_axi_vdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_vdma_0_1 || ORIG_REF_NAME==ZYNQ_CORE_axi_vdma_0_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_v_tc_0_0/ZYNQ_CORE_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_v_tc_0_0 || ORIG_REF_NAME==ZYNQ_CORE_v_tc_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_clk_wiz_0_0/ZYNQ_CORE_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_clk_wiz_0_0 || ORIG_REF_NAME==ZYNQ_CORE_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_DVI_Transmitter_0_0/ZYNQ_CORE_DVI_Transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_DVI_Transmitter_0_0 || ORIG_REF_NAME==ZYNQ_CORE_DVI_Transmitter_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_v_axi4s_vid_out_0_0/ZYNQ_CORE_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ZYNQ_CORE_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_rst_ps7_0_100M_0/ZYNQ_CORE_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_rst_ps7_0_100M_0 || ORIG_REF_NAME==ZYNQ_CORE_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_ps7_0_axi_periph_0/ZYNQ_CORE_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZYNQ_CORE_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_rst_ps7_0_50M_0/ZYNQ_CORE_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZYNQ_CORE_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_smc_1/ZYNQ_CORE_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_smc_1 || ORIG_REF_NAME==ZYNQ_CORE_axi_smc_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_util_vector_logic_0_0/ZYNQ_CORE_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_util_vector_logic_0_0 || ORIG_REF_NAME==ZYNQ_CORE_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_Pixclock_divider_0_0/ZYNQ_CORE_Pixclock_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_Pixclock_divider_0_0 || ORIG_REF_NAME==ZYNQ_CORE_Pixclock_divider_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_0/ZYNQ_CORE_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_pc_0 || ORIG_REF_NAME==ZYNQ_CORE_auto_pc_0} -quiet] -quiet

# XDC: bd/ZYNQ_CORE/ZYNQ_CORE_ooc.xdc
