webtalk_init -webtalk_dir C:\\Users\\yuwen\\Downloads\\Compressed\\26_VDMA_HDMI_TEST_720P_TF_TEST\\26_VDMA_HDMI_TEST_720P_TF_TEST\\VDMA_HDMI_TEST\\VDMA_HDMI_TEST.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-11-21 22:44:59" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "213228530_0_0_448" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "eu9g2nj0t59vl2lj6bv74dlup6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12500H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3110 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.891 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1732196250044" -context "sdk\\\\hardware/1732196250044"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1732196250044"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1732196250044"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1732196250044"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1732196250044"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1732196250044"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1732196250044"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1732196250044"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1732196250044"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1732196250044"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1732196250044"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1732200299584"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1732200299584"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1732200299584"
webtalk_add_data -client sdk -key DebugCount -value "26" -context "sdk\\\\bsp/1732200299584"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1732200299584"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1732200299584"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1732200299584"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1732200299584"
webtalk_transmit -clientid 1705681196 -regid "213228530_0_0_448" -xml C:\\Users\\yuwen\\Downloads\\Compressed\\26_VDMA_HDMI_TEST_720P_TF_TEST\\26_VDMA_HDMI_TEST_720P_TF_TEST\\VDMA_HDMI_TEST\\VDMA_HDMI_TEST.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\yuwen\\Downloads\\Compressed\\26_VDMA_HDMI_TEST_720P_TF_TEST\\26_VDMA_HDMI_TEST_720P_TF_TEST\\VDMA_HDMI_TEST\\VDMA_HDMI_TEST.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\yuwen\\Downloads\\Compressed\\26_VDMA_HDMI_TEST_720P_TF_TEST\\26_VDMA_HDMI_TEST_720P_TF_TEST\\VDMA_HDMI_TEST\\VDMA_HDMI_TEST.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
